### ISSUE TITLE
Showing and hiding alerts

### ISSUE THREAD

**Issue by line47** [fugacious/fugacious#102]
- [x] Only show temporary message alert when viewing the message after creation (for those receiving the message).
- [x] Only show message created alert to the user who created the message upon creation.
- [x] Deleted message - Update style of message deleted alert and the text for when a message is deleted 
-  [x] Deleted message - Don’t show the secret message
- [x] Only show created alerts on view number zero

<img width="391" alt="screen shot 2017-02-08 at 4 06 55 pm" src="https://cloud.githubusercontent.com/assets/1449852/22757420/a80050ea-ee18-11e6-9737-8a1913823f8e.png">

<img width="845" alt="screen shot 2017-02-08 at 4 06 14 pm" src="https://cloud.githubusercontent.com/assets/1449852/22757405/951965fc-ee18-11e6-815e-246029271432.png">

**Comment by jessieay** [comment]
Happy to pair on all of this.

If you'd like to get a jump start, getting flash messages to disappear after a certain amount of time is  going to require a little bit o' jquery http://stackoverflow.com/a/21467289

**Comment by line47** [comment]
This is almost complete I'm getting an issue when you view the message for the 2nd time only you get both alerts "Message created!" and "This message is temporary!"

<img width="710" alt="screen shot 2017-02-22 at 11 07 16 am" src="https://cloud.githubusercontent.com/assets/1449852/23221593/77b6b7ea-f8f3-11e6-86db-d0f71fbd0556.png">

**Comment by line47** [comment]
This issue was addressed with pr #111
