### ISSUE TITLE
Increase maximum number of hours allowed

### ISSUE THREAD

**Issue by rdpiazza** [fugacious/fugacious#126]
Recommend increasing the maximum number of hours that can be specified to greater than 48.

Use case: I used Fugacious to send the password for an encrypted form to a GSA help desk.  I'm not confident that anyone will process my form quickly, so I wanted to specify that the password would expire in a week.  The maximum I could specify was 48 hours, and I'm concerned that the link will expire before the help desk tech gets around to decrypting and processing my form.

**Comment by amoose** [comment]
48 hours was established by the cloud.gov team. I am closing this issue for now.
