### ISSUE TITLE
Enable coveralls for new organization

### ISSUE THREAD

**Issue by amoose** [fugacious/fugacious#33]
Please enable coveralls.io for fugacious/fugacious

**Comment by jgrevich** [comment]
enabled, we need to config+integrate with travis. I will close this once that is done.

**Comment by amoose** [comment]
Integration is working, however coveralls is reporting failures for 0.0% decrease. Looks like we need to update the threshold
- https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-120924694

**Comment by amoose** [comment]
@trevormast said
> It looks like Coveralls allows a decrease threshold to be stated:

![screen shot 2016-01-30 at 8 13 44 pm](https://cloud.githubusercontent.com/assets/15270272/12725122/fabf9c56-c8c5-11e5-8e4a-3dd2bcaa9b8e.png)

**Comment by jgrevich** [comment]
Good catch, thanks. I bumped it to 90% and 1%.
