### ISSUE TITLE
Coveralls tests not passing at -0.0% decrease in coverage

### ISSUE THREAD

**Issue by trevormast** [fugacious/fugacious#47]
It looks like Coveralls allows a decrease threshold to be stated:

![screen shot 2016-01-30 at 8 13 44 pm](https://cloud.githubusercontent.com/assets/15270272/12725122/fabf9c56-c8c5-11e5-8e4a-3dd2bcaa9b8e.png)

**Comment by amoose** [comment]
Moving to #33
