### ISSUE TITLE
As an Aidan, I want an easy way to create Fugacious links from the command line

### ISSUE THREAD

**Issue by afeld** [fugacious/fugacious#58]
For power users, I'm thinking something like

``` bash
$ echo $SOMETHING | curl -d @- https://fugacio.us/
https://fugacio.us/m/...
```

**Comment by afeld** [comment]
This would simplify things like https://github.com/18F/cg-docs/pull/262.

**Comment by jgrevich** [comment]
Working being done in https://github.com/fugacious/fugacious/pull/15. Consider it escalated :)

**Comment by amoose** [comment]
Valid request! Existing issue: https://github.com/fugacious/fugacious/issues/14
