### ISSUE TITLE
Fix spelling error in #info-panel #fork pane

### ISSUE THREAD

**Issue by salomoneb** [fugacious/fugacious#62]
"Please feel free to check out the source code at github. We welcome any **imporvements** or bug fixes that you can offer."

![imporvements](https://cloud.githubusercontent.com/assets/16308025/17488335/e6c69638-5d66-11e6-995d-bd2ba3b0ce53.png)

**Comment by jgrevich** [comment]
Thanks @salomoneb

**Comment by brittag** [comment]
I saw this at https://fugacious.18f.gov/ too and went to fix it, but I saw it's already fixed in the "dev" branch. It'd be nice for that live version to get this copy update. :D

**Comment by jgrevich** [comment]
Thanks @brittag. We'll have that pushed to prod ASAP.

**Comment by amoose** [comment]
Fixed!
