### ISSUE TITLE
Urgent: Create limit on hours until self-destruct

### ISSUE THREAD

**Issue by NoahKunin** [fugacious/fugacious#66]
@jgrevich : There's a very high limit to the # of hours you can set to a message.

Example:

<img width="1279" alt="screen shot 2016-09-25 at 10 51 28 pm" src="https://cloud.githubusercontent.com/assets/565071/18821302/00d1dc04-8373-11e6-8a37-b7c233b1c87d.png">

You eventually increase the value to something around the scale of `10000000000000` to throw an error. But that aside, the value should be much lower, for two reasons.

**1) Resource Exhaustion:** an adversary could create scripting to fill up storage over a period of time, and  since the data won't be deleted per the excessive time frame, resource exhaustion beyond capacity planning is possible.

**2) Allows for violation of policy / intent:** Users may fat finger a value much higher than attended. Example, _722_ hours instead of _72_ hours.

We'd like a hotfix on this as soon as is reasonable on the fugacious.18f.gov instance at minimum, as it will be a blocker to ATOs on systems that mention fugacious in their SSPs - ie, all of them. 😁 

Thank you!

**Comment by amoose** [comment]
I will jump on this today.

> Allows for violation of policy / intent 

What is a good hard limit here? 30 days?

**Comment by NoahKunin** [comment]
I think that's a Product Owner decision that I wouldn't want to micromanage. 

I know I'm only one user, in the context of 18F/govt, so my desires may not be representative. Wearing that hat, I'd put it much lower, at 120 hours.

**Comment by NoahKunin** [comment]
But one thing our security partners have made clear (DHS, DoD) is that anything beyond 30 days is not acceptable.

**Comment by amoose** [comment]
Understandable, I was looking for that value ☝️ and make it configurable

**Comment by amoose** [comment]
@jmcarp deployed to cloud.gov 👏  -- need to update DNS, @jgrevich ?

**Comment by amoose** [comment]
Confirmed https://fugacious.18f.gov/ is currently configured to limit retention to **48 hours**.

Thanks @jmcarp, @dlapiduz and @jgrevich! 👍
