### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by jmcarp** [fugacious/fugacious#81]
As a user of fugacious, I want to know that the deployed version is up to date (and it sounds like it isn't right now). Fugacious should be deployed automatically--e.g., on each tagged commit to master.

**Comment by amoose** [comment]
For transparency:
> Josh Carp (CHO) [1:18 PM]  
> hrm, i already put it on concourse, and i’ll have a patch for replacing whenever with sidekiq-cron later today

Josh is a machine 🚤

**Comment by jmcarp** [comment]
Happened in https://github.com/18F/cg-deploy-fugacious.
