### ISSUE TITLE
Update installation notes with Xcode and local Gemfile info

### ISSUE THREAD

**Issue by line47** [fugacious/fugacious#98]
Add the following to installation instructions:

===

Add to your local Gemfile.
```
source 'https://rubygems.org'
+git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }
ruby '2.3.3'
```
This sources github repos via https and will remove https warnings

===

[Xcode](https://developer.apple.com/xcode/)

**Comment by amoose** [comment]
Thanks @line47! This update has been accepted!
